<?php
/**
 * @file
 * This is the file description for Zillow Rules module.
 *
 * The Zillow Rules module creates a "Tour" node when using 
 * the VBO module.
 */

/**
 * Implements of hook_views_pre_render().
 *
 * This hook function is included to allow this example module to react when
 * views are being rendered, and call Rules to have any suitable reaction rules
 * fire off.
 *
 * @param <object> $view
 *   The view object that is going to be rendered.
 */
function zillow_rules_views_pre_render(&$view) {
  // Events are invoked by the event name, followed by the event variables in
  // the same order as they are listed in the event declaration. You can also
  // use rules_invoke_event_by_args() to call the event with all the variables
  // collected in an associative array – which is particularly useful if there
  // are a shifting number of variables.
  //rules_invoke_event('rules_example_event_view_render', $view->name);
  //dpm($view);
}